name: Release main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create a new production release
    uses: ./.github/workflows/_sem_release.yaml
    secrets:
      semantic-release-token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
